version:  '3'
services:
  web:
    container_name: web
    image: express-app
    ports:
    - 8080:8080
    volumes:
    - $PWD:/usr/src/app
    networks:
    - webnet
    links:
    - db
    depends_on:
    - db
  db:
    container_name: postgres
    image:  postgres:12
    environment:
    - POSTGRES_PASSWORD=123
    - POSTGRES_USER=oscar
    volumes:
    - $PWD/data:/var/lib/postgresql/data
    networks:
    - webnet
networks:
  webnet:
  
